id = "yap"
name = "YAP!"
version = "0.1.0"
schema_version = 1
authors = ["Valaphee <valaphee@valaphee.com>"]
description = "YAP! Programming Language"
repository = "https://github.com/yap-lang/zed-yap"

[grammars.yap]
repository = "https://github.com/yap-lang/tree-sitter-yap"
rev = "a253aa1a479582391651fbedae19ca13e890cc4e"
